routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\PostController;
use App\Http\Controllers\Backend\SiteController;
use App\Http\Controllers\Backend\BrandController;
use App\Http\Controllers\Backend\OrderController;
use App\Http\Controllers\Backend\SlideController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\CustomerController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\Auth\LoginController;
use App\Http\Controllers\Backend\PostCategoryController;

Route::middleware(['auth', 'preventBackHistory', 'role:admin'])->group(function () {
    Route::get('/', [SiteController::class, 'index'])->name('home');

    Route::get('property/get-list', [\App\Http\Controllers\Backend\PropertyController::class, 'getList'])->name('property.get-list');
    Route::resource('property', \App\Http\Controllers\Backend\PropertyController::class)->except(['show']);

    Route::resource('categories', CategoryController::class)->except(['show']);
    Route::get('categories/move/{id}/{type}', [CategoryController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('categories.move');


    Route::resource('brands', BrandController::class)->except(['show']);
    Route::get('brands/move/{id}/{type}', [BrandController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('brands.move');


    Route::resource('products', ProductController::class);
    Route::get('products-import', [ProductController::class, 'import'])->name('products.import');
    Route::post('products-importing', [ProductController::class, 'importProducts'])->name('products.import-products');

    Route::resource('slides', SlideController::class)->except('show');
    Route::get('slides/move/{id}/{type}', [SlideController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('slides.move');

    /* Page routes */
    Route::resource('pages', \App\Http\Controllers\Backend\PageController::class)->except(['show']);
    Route::post('pages/delete-image/{id}', [\App\Http\Controllers\Backend\PageController::class, 'deleteImage'])
        ->name('pages.delete-image');
    Route::get('pages/move/{id}/{type}', [\App\Http\Controllers\Backend\PageController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('pages.move');

    /* User routes */
    Route::post('users/delete-thumb/{id}', [\App\Http\Controllers\Backend\UserController::class, 'deleteThumb'])
        ->name('users.delete-image');
    Route::resource('users', \App\Http\Controllers\Backend\UserController::class);

    Route::resource('faq', \App\Http\Controllers\Backend\FaqController::class)->except(['show']);
    Route::resource('config', \App\Http\Controllers\Backend\ConfigController::class)->except(['show']);
    Route::resource('translates', \App\Http\Controllers\Backend\TranslateController::class)->except(['show']);

    /* Main Info routes */
    Route::post('main-info/delete-logo/{id}', [\App\Http\Controllers\Backend\MainInfoController::class, 'deleteLogo'])
        ->name('main-info.delete-logo');
    Route::post('main-info/delete-favicon/{id}', [\App\Http\Controllers\Backend\MainInfoController::class, 'deleteFavicon'])
        ->name('main-info.delete-favicon');
    Route::get('main-info', [\App\Http\Controllers\Backend\MainInfoController::class, 'index'])->name('main-info');
    Route::put('main-info', [\App\Http\Controllers\Backend\MainInfoController::class, 'update'])->name('main-info.update');

    /* Image Upload route */
    Route::post('ckeditor/image_upload', [\App\Http\Controllers\CkeditorController::class, 'upload'])->name('ckeupload');

    Route::resource('tags', \App\Http\Controllers\Backend\TagController::class);
    Route::prefix('blog')->name('blog.')->group(function () {
        Route::resource('categories', PostCategoryController::class);
        Route::get('categories/move/{id}/{type}', [PostCategoryController::class, 'move'])
            ->where('type', 'up|down')
            ->where('id', '[0-9]+')
            ->name('categories.move');
        Route::resource('posts', \App\Http\Controllers\Backend\PostController::class);
    });
    Route::get('posts/tag-list', [PostController::class, 'tagList'])->name('posts.tag-list');


    Route::resource('orders', \App\Http\Controllers\Backend\OrderController::class);
    Route::get('orders/reversal/{transaction_id}', [OrderController::class, 'reversal'])->name('orders.reversal');

    Route::resource('customers', CustomerController::class)->except(['show']);

    Route::prefix('photos')->name('photos.')->group(function () {
        Route::get('index', [\App\Http\Controllers\Backend\PhotoController::class, 'index'])->name('index');
        Route::get('folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderIndex'])->name('folder');
        Route::get('trash', [\App\Http\Controllers\Backend\PhotoController::class, 'trashIndex'])->name('trash');
        Route::get('restore', [\App\Http\Controllers\Backend\PhotoController::class, 'restore'])->name('restore');
        Route::post('create', [\App\Http\Controllers\Backend\PhotoController::class, 'create'])->name('create');
        Route::get('update', [\App\Http\Controllers\Backend\PhotoController::class, 'update'])->name('update');
        Route::post('update', [\App\Http\Controllers\Backend\PhotoController::class, 'update'])->name('update.submit');
        Route::post('size', [\App\Http\Controllers\Backend\PhotoController::class, 'size'])->name('size.submit');
        Route::get('create-folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderCreate'])->name('create-folder');
        Route::get('delete-folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderDelete'])->name('delete-folder');
        Route::get('update-folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderUpdate'])->name('update-folder');
        Route::post('update-folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderUpdate'])->name('update-folder.submit');
        Route::post('create-folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderCreate'])->name('create-folder.submit');
        Route::post('delete', [\App\Http\Controllers\Backend\PhotoController::class, 'delete'])->name('delete');
        Route::post('soft-delete', [\App\Http\Controllers\Backend\PhotoController::class, 'softDelete'])->name('softDelete');
        Route::post('crop', [\App\Http\Controllers\Backend\PhotoController::class, 'crop'])->name('crop');
        Route::get('sort', [\App\Http\Controllers\Backend\PhotoController::class, 'sort'])->name('sort');
        Route::post('render-gallery', [\App\Http\Controllers\Backend\PhotoController::class, 'renderGallery'])->name('render-gallery');
        Route::post('get-size', [\App\Http\Controllers\Backend\PhotoController::class, 'getSize'])->name('get-size');
    });

});

Route::middleware(['preventBackHistory'])->group(function () {
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->name('login.login');
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Frontend\SiteController;
use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\OrderController;
use App\Http\Controllers\Frontend\StaticController;
use App\Http\Controllers\Frontend\ContactController;
use App\Http\Controllers\Frontend\ProfileController;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;


Route::prefix(LaravelLocalization::setLocale())->middleware(['localize'])->group(function () {
    Route::get('/', [SiteController::class, 'index'])->name('home');

    Route::post('/product/fast-buy/{id}', [\App\Http\Controllers\Frontend\ProductController::class, 'fastBuy'])->name('fast-buy');

    Route::get('/products/filter', [\App\Http\Controllers\Frontend\ProductController::class, 'filter'])
        ->name('products.filter');
    Route::get('/products/{slug}', [\App\Http\Controllers\Frontend\ProductController::class, 'index'])
        ->where('slug', '[\w\-]+')
        ->name('products');

    Route::get('/search', [\App\Http\Controllers\Frontend\SearchController::class, 'index'])
        ->middleware(\App\Http\Middleware\SearchQuery::class)->name('search');
    Route::get('/search/filter', [\App\Http\Controllers\Frontend\SearchController::class, 'filter'])->name('search.filter');
    Route::get('/product/{slug}', [\App\Http\Controllers\Frontend\ProductController::class, 'index'])->name('products.category')
        ->where('slug', '[\w\-]+');
    Route::get('/product/{slug}', [\App\Http\Controllers\Frontend\ProductController::class, 'view'])->name('product')
        ->where('slug', '[\w\-]+');


    Route::get('/blog', [\App\Http\Controllers\Frontend\BlogController::class, 'index'])->name('blog.index');
    Route::name('blog.')->prefix('blog')->group(function () {
        Route::get('/{slug}', [\App\Http\Controllers\Frontend\BlogController::class, 'index'])->name('category')
            ->where('slug', '[\w\-]+');
        Route::get('/post/{slug}', [\App\Http\Controllers\Frontend\BlogController::class, 'view'])->name('post')
            ->where('slug', '[\w\-]+');
        Route::get('/tag/{slug}', [\App\Http\Controllers\Frontend\BlogController::class, 'tag'])->name('tag')
            ->where('slug', '[\w\-]+');
        Route::get('/search', [\App\Http\Controllers\Frontend\BlogController::class, 'search'])->name('search');
    });


    Route::get('/page/{slug}', [StaticController::class, 'view'])
        ->name('page')
        ->where('slug', '[\w\-]+');
    Route::get('/contact', [ContactController::class, 'index'])->name('contact');
    Route::get('/faq', [StaticController::class, 'faq'])->name('faq');
    Route::post('/contact/send', [ContactController::class, 'send'])->name('contact.send_message');

    Route::get('/favorites', [\App\Http\Controllers\Frontend\FavoriteController::class, 'index'])->name('favorites');
    Route::get('/favorite/add', [\App\Http\Controllers\Frontend\FavoriteController::class, 'add'])->name('favorite.add');
    Route::get('/favorite/remove', [\App\Http\Controllers\Frontend\FavoriteController::class, 'remove'])->name('favorite.remove');
    Route::get('/favorite/filter', [\App\Http\Controllers\Frontend\FavoriteController::class, 'filter'])->name('favorite.filter');



    Route::get('/cart', [CartController::class, 'index'])->name('cart');
    Route::get('/cart/add', [\App\Http\Controllers\Frontend\CartController::class, 'add'])->name('cart.add');
    Route::get('/cart/update', [\App\Http\Controllers\Frontend\CartController::class, 'update'])->name('cart.update');
    Route::get('/cart/remove', [\App\Http\Controllers\Frontend\CartController::class, 'remove'])->name('cart.remove');

    Route::get('/checkout', [\App\Http\Controllers\Frontend\CheckoutController::class, 'index'])->name('checkout');

    Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
        Route::post('/send', [OrderController::class, 'send'])->name('send');
        Route::get('/thank-you', [OrderController::class, 'thankYou'])->name('thankYou');
        Route::get('/payment-result', [OrderController::class, 'paymentResult'])->name('payment.result');
        Route::get('/fail', [OrderController::class, 'fail'])->name('fail');
    });

    Route::group(['middleware' => ['auth:siteCustomer']], function () {
        Route::get('/history', [ProfileController::class, 'history'])->name('history');
        Route::get('/history/{id}', [ProfileController::class, 'historyView'])->name('history.view');
        Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
        Route::get('/profile/change-password', [ProfileController::class, 'changePasswordForm'])->name('profile.change-password');
        Route::put('/profile/change-password', [ProfileController::class, 'changePassword'])->name('profile.change-password.submit');
        Route::put('/profile/update', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::get('/profile/delete', [ProfileController::class, 'delete'])->name('profile.delete');
    });

    Route::middleware(['preventBackHistory'])->group(function () {
        Route::get('login', [\App\Http\Controllers\Frontend\Auth\LoginController::class, 'showLoginForm'])->name('login');
        Route::post('login', [\App\Http\Controllers\Frontend\Auth\LoginController::class, 'login'])->name('login.submit');
        Route::get('register', [\App\Http\Controllers\Frontend\Auth\RegisterController::class, 'showRegistrationForm'])->name('register');
        Route::post('register', [\App\Http\Controllers\Frontend\Auth\RegisterController::class, 'register'])->name('register.submit');
        Route::get('logout', [\App\Http\Controllers\Frontend\Auth\LoginController::class, 'logout'])->name('logout');

        Route::get('reset-password', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'showResetPasswordForm'])->name('reset-password');
        Route::post('reset-password', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'showResetPasswordForm'])->name('reset-password.submit');
        Route::get('send-reset-code', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'showCodeInputForm'])->name('show-code-form');
        Route::post('send-reset-code', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'showCodeInputForm'])->name('show-code-form.submit');
        Route::get('change-password', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'changePassword'])->name('change-password');
        Route::post('change-password', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'changePassword'])->name('change-password.submit');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    const DEFAULT_THUMB = 'user.png';

    public function getFullNameAttribute()
    {
        return "{$this->name}";
    }

    public static function create($name, $email, $status, $password)
    {

        $model = new static();

        $model->name = $name;
        $model->email = $email;
        $model->status = $status;
        $model->password = Hash::make($password);

        return $model;
    }

    public function edit($name, $email, $password)
    {
        $this->name = $name;
        $this->email = $email;

        if ($password) {
            $this->password = Hash::make($password);
        }
    }

    public function attachThumb($thumb)
    {
        $this->thumb = $thumb;
    }

    public function detachThumb()
    {
        $this->thumb = null;
    }
    public function isAdmin() {
        return $this->roles()->where('name', 'admin')->exists();
    }

    public function posts()
    {
        return $this->hasMany(Post::class,'author_id')->orderByDesc('published_at');
    }
}

app/Http/Controllers/Backend/BaseController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\RedirectResponse;

class BaseController
{
    /**
     * @param string $route
     * @param string|null $type
     * @param string|null $message
     * @return RedirectResponse
     */
    protected function redirect(string $route, ?string $type = 'success', ?string $message = null): RedirectResponse
    {
        return redirect()->route($route)
            ->with($type, trans($message ?? "form.{$type}.save"));
    }
}

app/Http/Controllers/Backend/SiteController.php
<?php

namespace App\Http\Controllers\Backend;

class SiteController extends BaseController
{

    public function index()
    {
//        echo '<img src='.get_image('5SG2qgHDQmM5TfPT7iWVoL7WZPQovmb7QQabazUD.png','','list').'>';
//        dd(get_image('5SG2qgHDQmM5TfPT7iWVoL7WZPQovmb7QQabazUD.png','','list'));
//        die();
        return view('backend.site.index');
    }
}

resources/views/backend/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title') | Admin Panel</title>
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    @include('backend.layouts.styles')

{{--    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">--}}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="{{ route('admin.home') }}" class="brand-link">
            <img src="{{ asset('images/AdminLogo.png') }}" class="brand-image img-circle elevation-3" style="opacity: .8">
            <span class="brand-text font-weight-light">@lang('admin_panel_name')</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img src="{{ auth()->user()->thumb ? asset("storage/users/" . auth()->user()->thumb) : asset('images/' . \App\Models\User::DEFAULT_THUMB) }}" class="img-circle elevation-2" alt="User Image">
                </div>
                <div class="info">
                    <a href="{{ route('admin.users.show', auth()->id()) }}" class="d-block">{{ auth()->user()->full_name }}</a>
                </div>
            </div>

            @include('backend.layouts.menu')

        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        @include('backend.layouts.breadcrumb')

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                @include('backend.layouts.notification')
                @yield('content')
            </div><!-- /.container-fluid -->
        </section>
    </div>

    @include('backend.layouts.footer')

    @yield('end_load')
</div>
<!-- ./wrapper -->
    @include('backend.layouts.scripts')
</body>
</html>

resources/views/backend/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin Panel</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('assets/backend/css/fontawesome/css/all.min.css') }}">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="{{ asset('assets/backend/css/icheck-bootstrap.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('assets/backend/css/adminlte.min.css') }}">
</head>
<body class="hold-transition login-page">

    @yield('content')


    <!-- jQuery -->
    <script src="{{ asset('assets/backend/js/jquery.min.js') }}"></script>
    <!-- Bootstrap 4 -->
    <script src="{{ asset('assets/backend/js/bootstrap.bundle.min.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('assets/backend/js/adminlte.min.js') }}"></script>
</body>
</html>

resources/views/backend/layouts/breadcrumb.blade.php
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">@yield('title')</h1>
            </div><!-- /.col -->
            @if(!Route::is('admin.home'))
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">{{ trans('admin.home_page') }}</a></li>
                        @hasSection('title')
                            <li class="breadcrumb-item active">@yield('title')</li>
                        @endif
                    </ol>
                </div><!-- /.col -->
            @endif
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

resources/views/backend/layouts/footer.blade.php
<!-- Sidebar Menu -->
<footer class="main-footer">
    <strong>Copyright &copy; 2021.</strong>
    All rights reserved.
</footer>
<!-- /.sidebar-menu -->

resources/views/backend/layouts/menu.blade.php
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class  with font-awesome or any other icon font library -->
        <li class="nav-item">
            <a href="{{ route('admin.pages.index') }}" class="nav-link">
                <i class="nav-icon fas fa-book"></i>
                <p>
                    @lang('admin.menu.pages')
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.categories.index') }}" class="nav-link">
                <i class="nav-icon fas fa-align-left"></i>
                <p>
                    @lang('admin.menu.categories')
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.brands.index') }}" class="nav-link">
                <i class="nav-icon fas fa-align-left"></i>
                <p>
                    @lang('admin.menu.brands')
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.property.index') }}" class="nav-link">
                <i class="nav-icon fas fa-list-alt"></i>
                <p>
                    @lang('admin.menu.properties')
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.products.index') }}" class="nav-link">
                <i class="nav-icon fas fa-shopping-cart"></i>
                <p>
                    @lang('admin.menu.products')
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.orders.index') }}" class="nav-link">
                <i class="nav-icon fas fa-shopping-basket"></i>
                <p>
                    @lang('admin.menu.orders')
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.customers.index') }}" class="nav-link">
                <i class="nav-icon fas fa-users"></i>
                <p>
                    @lang('admin.menu.customers')
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.slides.index') }}" class="nav-link">
                <i class="nav-icon fas fa-image"></i>
                <p>
                    @lang('admin.menu.slides')
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.faq.index') }}" class="nav-link">
                <i class="nav-icon fas fa-question"></i>
                <p>
                    @lang('admin.menu.faq')
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.users.index') }}" class="nav-link">
                <i class="nav-icon fas fa-user"></i>
                <p>
                    @lang('admin.menu.users')
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.tags.index') }}" class="nav-link">
                <i class="nav-icon fas fa-tags"></i>
                <p>
                    @lang('admin.menu.tags')
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="javascript:void(0);" class="nav-link">
                <i class="nav-icon fas fa-newspaper"></i>
                <p>
                    @lang('admin.menu.blog')
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="{{ route('admin.blog.categories.index') }}" class="nav-link">
                        <p>
                            <i class="nav-icon">-</i>
                            @lang('admin.menu.categories')
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.blog.posts.index') }}" class="nav-link">
                        <p>
                            <i class="nav-icon">-</i>
                            @lang('admin.menu.posts')
                        </p>
                    </a>
                </li>
            </ul>
        </li>
        <li class="nav-item">
            <a href="javascript:void(0);" class="nav-link">
                <i class="nav-icon fas fa-cogs"></i>
                <p>
                    @lang('admin.menu.settings')
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="{{ route('admin.main-info') }}" class="nav-link">
                        <p>
                            <i class="nav-icon">-</i>
                            @lang('admin.menu.main-info')
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.config.index') }}" class="nav-link">
                        <p>
                            <i class="nav-icon">-</i>
                            @lang('admin.menu.configs')
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.translates.index') }}" class="nav-link">
                        <p>
                            <i class="nav-icon">-</i>
                            @lang('admin.menu.translates')
                        </p>
                    </a>
                </li>
            </ul>
        </li>
    </ul>

    <a data-href="{{ route('admin.logout') }}" id="logout-button">{{ trans('admin.logout') }}</a>
</nav>

resources/views/backend/layouts/notification.blade.php
@if(session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

@if(session('error'))
    <div class="alert alert-danger">
        {{ session('error') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

resources/views/backend/layouts/slug_generate_scripts.blade.php
<script>
    let _title = $('.autoGenerateSlug');

    _title.on('keyup', function() {
        _lang=$('.tab-pane.fade.show.active').data('lang');
        let _slug = $('#slug-'+_lang);
        _slug.val();
        let txt=convertToSlug($(this).val());
        _slug.val(txt)
    });
    function convertToSlug(text) {
        return text.toLowerCase()
            .replace(/ /g, '-')
            .replace(/[^\w-]+/g, '');
    }
</script>

resources/views/backend/layouts/styles.blade.php
<link rel="stylesheet" href="{{ asset('assets/backend/css/fontawesome/css/all.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/daterangepicker.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/fileinput.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/tempusdominus-bootstrap-4.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/adminlte.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/OverlayScrollbars.min.css') }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.min.css" crossorigin="anonymous">
<link rel="stylesheet" href="{{ asset('assets/backend/css/admin.css') }}">