routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\PostController;
use App\Http\Controllers\Backend\SiteController;
use App\Http\Controllers\Backend\BrandController;
use App\Http\Controllers\Backend\OrderController;
use App\Http\Controllers\Backend\SlideController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\CustomerController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\Auth\LoginController;
use App\Http\Controllers\Backend\PostCategoryController;

Route::middleware(['auth', 'preventBackHistory', 'role:admin'])->group(function () {
    Route::get('/', [SiteController::class, 'index'])->name('home');

    Route::get('property/get-list', [\App\Http\Controllers\Backend\PropertyController::class, 'getList'])->name('property.get-list');
    Route::resource('property', \App\Http\Controllers\Backend\PropertyController::class)->except(['show']);

    Route::resource('categories', CategoryController::class)->except(['show']);
    Route::get('categories/move/{id}/{type}', [CategoryController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('categories.move');


    Route::resource('brands', BrandController::class)->except(['show']);
    Route::get('brands/move/{id}/{type}', [BrandController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('brands.move');


    Route::resource('products', ProductController::class);
    Route::get('products-import', [ProductController::class, 'import'])->name('products.import');
    Route::post('products-importing', [ProductController::class, 'importProducts'])->name('products.import-products');

    Route::resource('slides', SlideController::class)->except('show');
    Route::get('slides/move/{id}/{type}', [SlideController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('slides.move');

    /* Page routes */
    Route::resource('pages', \App\Http\Controllers\Backend\PageController::class)->except(['show']);
    Route::post('pages/delete-image/{id}', [\App\Http\Controllers\Backend\PageController::class, 'deleteImage'])
        ->name('pages.delete-image');
    Route::get('pages/move/{id}/{type}', [\App\Http\Controllers\Backend\PageController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('pages.move');

    /* User routes */
    Route::post('users/delete-thumb/{id}', [\App\Http\Controllers\Backend\UserController::class, 'deleteThumb'])
        ->name('users.delete-image');
    Route::resource('users', \App\Http\Controllers\Backend\UserController::class);

    Route::resource('faq', \App\Http\Controllers\Backend\FaqController::class)->except(['show']);
    Route::resource('config', \App\Http\Controllers\Backend\ConfigController::class)->except(['show']);
    Route::resource('translates', \App\Http\Controllers\Backend\TranslateController::class)->except(['show']);

    /* Main Info routes */
    Route::post('main-info/delete-logo/{id}', [\App\Http\Controllers\Backend\MainInfoController::class, 'deleteLogo'])
        ->name('main-info.delete-logo');
    Route::post('main-info/delete-favicon/{id}', [\App\Http\Controllers\Backend\MainInfoController::class, 'deleteFavicon'])
        ->name('main-info.delete-favicon');
    Route::get('main-info', [\App\Http\Controllers\Backend\MainInfoController::class, 'index'])->name('main-info');
    Route::put('main-info', [\App\Http\Controllers\Backend\MainInfoController::class, 'update'])->name('main-info.update');

    /* Image Upload route */
    Route::post('ckeditor/image_upload', [\App\Http\Controllers\CkeditorController::class, 'upload'])->name('ckeupload');

    Route::resource('tags', \App\Http\Controllers\Backend\TagController::class);
    Route::prefix('blog')->name('blog.')->group(function () {
        Route::resource('categories', PostCategoryController::class);
        Route::get('categories/move/{id}/{type}', [PostCategoryController::class, 'move'])
            ->where('type', 'up|down')
            ->where('id', '[0-9]+')
            ->name('categories.move');
        Route::resource('posts', \App\Http\Controllers\Backend\PostController::class);
    });
    Route::get('posts/tag-list', [PostController::class, 'tagList'])->name('posts.tag-list');


    Route::resource('orders', \App\Http\Controllers\Backend\OrderController::class);
    Route::get('orders/reversal/{transaction_id}', [OrderController::class, 'reversal'])->name('orders.reversal');

    Route::resource('customers', CustomerController::class)->except(['show']);

    Route::prefix('photos')->name('photos.')->group(function () {
        Route::get('index', [\App\Http\Controllers\Backend\PhotoController::class, 'index'])->name('index');
        Route::get('folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderIndex'])->name('folder');
        Route::get('trash', [\App\Http\Controllers\Backend\PhotoController::class, 'trashIndex'])->name('trash');
        Route::get('restore', [\App\Http\Controllers\Backend\PhotoController::class, 'restore'])->name('restore');
        Route::post('create', [\App\Http\Controllers\Backend\PhotoController::class, 'create'])->name('create');
        Route::get('update', [\App\Http\Controllers\Backend\PhotoController::class, 'update'])->name('update');
        Route::post('update', [\App\Http\Controllers\Backend\PhotoController::class, 'update'])->name('update.submit');
        Route::post('size', [\App\Http\Controllers\Backend\PhotoController::class, 'size'])->name('size.submit');
        Route::get('create-folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderCreate'])->name('create-folder');
        Route::get('delete-folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderDelete'])->name('delete-folder');
        Route::get('update-folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderUpdate'])->name('update-folder');
        Route::post('update-folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderUpdate'])->name('update-folder.submit');
        Route::post('create-folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderCreate'])->name('create-folder.submit');
        Route::post('delete', [\App\Http\Controllers\Backend\PhotoController::class, 'delete'])->name('delete');
        Route::post('soft-delete', [\App\Http\Controllers\Backend\PhotoController::class, 'softDelete'])->name('softDelete');
        Route::post('crop', [\App\Http\Controllers\Backend\PhotoController::class, 'crop'])->name('crop');
        Route::get('sort', [\App\Http\Controllers\Backend\PhotoController::class, 'sort'])->name('sort');
        Route::post('render-gallery', [\App\Http\Controllers\Backend\PhotoController::class, 'renderGallery'])->name('render-gallery');
        Route::post('get-size', [\App\Http\Controllers\Backend\PhotoController::class, 'getSize'])->name('get-size');
    });

});

Route::middleware(['preventBackHistory'])->group(function () {
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->name('login.login');
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Frontend\SiteController;
use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\OrderController;
use App\Http\Controllers\Frontend\StaticController;
use App\Http\Controllers\Frontend\ContactController;
use App\Http\Controllers\Frontend\ProfileController;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;


Route::prefix(LaravelLocalization::setLocale())->middleware(['localize'])->group(function () {
    Route::get('/', [SiteController::class, 'index'])->name('home');

    Route::post('/product/fast-buy/{id}', [\App\Http\Controllers\Frontend\ProductController::class, 'fastBuy'])->name('fast-buy');

    Route::get('/products/filter', [\App\Http\Controllers\Frontend\ProductController::class, 'filter'])
        ->name('products.filter');
    Route::get('/products/{slug}', [\App\Http\Controllers\Frontend\ProductController::class, 'index'])
        ->where('slug', '[\w\-]+')
        ->name('products');

    Route::get('/search', [\App\Http\Controllers\Frontend\SearchController::class, 'index'])
        ->middleware(\App\Http\Middleware\SearchQuery::class)->name('search');
    Route::get('/search/filter', [\App\Http\Controllers\Frontend\SearchController::class, 'filter'])->name('search.filter');
    Route::get('/product/{slug}', [\App\Http\Controllers\Frontend\ProductController::class, 'index'])->name('products.category')
        ->where('slug', '[\w\-]+');
    Route::get('/product/{slug}', [\App\Http\Controllers\Frontend\ProductController::class, 'view'])->name('product')
        ->where('slug', '[\w\-]+');


    Route::get('/blog', [\App\Http\Controllers\Frontend\BlogController::class, 'index'])->name('blog.index');
    Route::name('blog.')->prefix('blog')->group(function () {
        Route::get('/{slug}', [\App\Http\Controllers\Frontend\BlogController::class, 'index'])->name('category')
            ->where('slug', '[\w\-]+');
        Route::get('/post/{slug}', [\App\Http\Controllers\Frontend\BlogController::class, 'view'])->name('post')
            ->where('slug', '[\w\-]+');
        Route::get('/tag/{slug}', [\App\Http\Controllers\Frontend\BlogController::class, 'tag'])->name('tag')
            ->where('slug', '[\w\-]+');
        Route::get('/search', [\App\Http\Controllers\Frontend\BlogController::class, 'search'])->name('search');
    });


    Route::get('/page/{slug}', [StaticController::class, 'view'])
        ->name('page')
        ->where('slug', '[\w\-]+');
    Route::get('/contact', [ContactController::class, 'index'])->name('contact');
    Route::get('/faq', [StaticController::class, 'faq'])->name('faq');
    Route::post('/contact/send', [ContactController::class, 'send'])->name('contact.send_message');

    Route::get('/favorites', [\App\Http\Controllers\Frontend\FavoriteController::class, 'index'])->name('favorites');
    Route::get('/favorite/add', [\App\Http\Controllers\Frontend\FavoriteController::class, 'add'])->name('favorite.add');
    Route::get('/favorite/remove', [\App\Http\Controllers\Frontend\FavoriteController::class, 'remove'])->name('favorite.remove');
    Route::get('/favorite/filter', [\App\Http\Controllers\Frontend\FavoriteController::class, 'filter'])->name('favorite.filter');



    Route::get('/cart', [CartController::class, 'index'])->name('cart');
    Route::get('/cart/add', [\App\Http\Controllers\Frontend\CartController::class, 'add'])->name('cart.add');
    Route::get('/cart/update', [\App\Http\Controllers\Frontend\CartController::class, 'update'])->name('cart.update');
    Route::get('/cart/remove', [\App\Http\Controllers\Frontend\CartController::class, 'remove'])->name('cart.remove');

    Route::get('/checkout', [\App\Http\Controllers\Frontend\CheckoutController::class, 'index'])->name('checkout');

    Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
        Route::post('/send', [OrderController::class, 'send'])->name('send');
        Route::get('/thank-you', [OrderController::class, 'thankYou'])->name('thankYou');
        Route::get('/payment-result', [OrderController::class, 'paymentResult'])->name('payment.result');
        Route::get('/fail', [OrderController::class, 'fail'])->name('fail');
    });

    Route::group(['middleware' => ['auth:siteCustomer']], function () {
        Route::get('/history', [ProfileController::class, 'history'])->name('history');
        Route::get('/history/{id}', [ProfileController::class, 'historyView'])->name('history.view');
        Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
        Route::get('/profile/change-password', [ProfileController::class, 'changePasswordForm'])->name('profile.change-password');
        Route::put('/profile/change-password', [ProfileController::class, 'changePassword'])->name('profile.change-password.submit');
        Route::put('/profile/update', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::get('/profile/delete', [ProfileController::class, 'delete'])->name('profile.delete');
    });

    Route::middleware(['preventBackHistory'])->group(function () {
        Route::get('login', [\App\Http\Controllers\Frontend\Auth\LoginController::class, 'showLoginForm'])->name('login');
        Route::post('login', [\App\Http\Controllers\Frontend\Auth\LoginController::class, 'login'])->name('login.submit');
        Route::get('register', [\App\Http\Controllers\Frontend\Auth\RegisterController::class, 'showRegistrationForm'])->name('register');
        Route::post('register', [\App\Http\Controllers\Frontend\Auth\RegisterController::class, 'register'])->name('register.submit');
        Route::get('logout', [\App\Http\Controllers\Frontend\Auth\LoginController::class, 'logout'])->name('logout');

        Route::get('reset-password', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'showResetPasswordForm'])->name('reset-password');
        Route::post('reset-password', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'showResetPasswordForm'])->name('reset-password.submit');
        Route::get('send-reset-code', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'showCodeInputForm'])->name('show-code-form');
        Route::post('send-reset-code', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'showCodeInputForm'])->name('show-code-form.submit');
        Route::get('change-password', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'changePassword'])->name('change-password');
        Route::post('change-password', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'changePassword'])->name('change-password.submit');
    });
});

app/Http/Controllers/Backend/BaseController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\RedirectResponse;

class BaseController
{
    /**
     * @param string $route
     * @param string|null $type
     * @param string|null $message
     * @return RedirectResponse
     */
    protected function redirect(string $route, ?string $type = 'success', ?string $message = null): RedirectResponse
    {
        return redirect()->route($route)
            ->with($type, trans($message ?? "form.{$type}.save"));
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php
declare(strict_types=1);

namespace App\Http\Controllers\Backend;

use Exception;
use RuntimeException;
use App\Models\Category;
use App\Helpers\NodeHelper;
use App\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use App\Services\manager\CategoryService;
use Itstructure\GridView\DataProviders\EloquentDataProvider;
use App\Http\Requests\Category\{CategoryCreateRequest, CategoryUpdateRequest};

class CategoryController extends Controller
{
    private $categoryService;

    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    public function index()
    {
        $query = Category::query()->withDepth()->defaultOrder();
        $dataProvider = new EloquentDataProvider($query);

        return view('backend.categories.index', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function create()
    {
        $parents = (new NodeHelper(Category::class))->map();

        return view('backend.categories.create', compact('parents'));
    }

    public function store(CategoryCreateRequest $request)
    {
        try {
            $this->categoryService->create($request);
            return redirect()->route('admin.categories.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {dd($e->getMessage());}
    }

    public function show(Category $category)
    {
        return view('backend.categories.view', [
            'category' => $category
        ]);
    }

    public function edit(Category $category)
    {
        $parents = (new NodeHelper($category))->map();

        return view('backend.categories.update', compact('category', 'parents'));
    }

    public function update(CategoryUpdateRequest $request, Category $category)
    {
        try {
            $this->categoryService->update($request, $category);
            return redirect()->route('admin.categories.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {}
    }

    public function destroy(Category $category): RedirectResponse
    {
        try {
            $this->categoryService->remove($category);
            return redirect()->route('admin.categories.index');
        } catch (RuntimeException $e) {
            return redirect()->route('admin.categories.index')->with('error', $e->getMessage());
        }
    }

    public function move(int $id, string $type): RedirectResponse
    {
        $category = Category::findOrFail($id);
        ($type == 'up') ? $category->up() : $category->down();

        return redirect()->back();
    }
}

app/Http/Controllers/Backend/SiteController.php
<?php

namespace App\Http\Controllers\Backend;

class SiteController extends BaseController
{

    public function index()
    {
//        echo '<img src='.get_image('5SG2qgHDQmM5TfPT7iWVoL7WZPQovmb7QQabazUD.png','','list').'>';
//        dd(get_image('5SG2qgHDQmM5TfPT7iWVoL7WZPQovmb7QQabazUD.png','','list'));
//        die();
        return view('backend.site.index');
    }
}

resources/views/backend/faqs/create.blade.php
@extends('backend.layouts.app')

@section('title', trans('admin.new_faq'))

@section('content')
    <div class="mt-3">
        <div>
            <form action="{{ route('admin.faq.store') }}" method="POST">
                @csrf
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-primary">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="language">@lang('admin.language')</label>
                                    <select id="language" class="form-control @error('language') is-invalid @enderror" name="language">
                                        @foreach(LaravelLocalization::getSupportedLanguagesKeys() as $locale)
                                            <option value="{{$locale}}" @if($locale == old('language')) selected @endif>{{ $locale }}</option>
                                        @endforeach
                                    </select>
                                    @error('language')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="question">@lang('admin.question')</label>
                                    <input type="text" id="question" class="form-control @error('question') is-invalid @enderror" name="question" value="{{ old('question') }}">
                                    @error('question')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="answer">@lang('admin.answer')</label>
                                    <textarea id="answer" class="form-control @error('answer') is-invalid @enderror" name="answer" cols="30" rows="10">{{ old('answer') }}</textarea>
                                    @error('answer')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <div class="float-right">
                                        <label for="status">@lang('admin.status.status')</label>
                                        <label class="switch switch-success">
                                            <input type="checkbox" name="status" id="status"
                                                   @if((bool) old('status')==1) checked @endif>
                                            <span class="slider round"></span>
                                        </label>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <input type="submit" value="@lang('admin.save')" class="btn btn-success float-right">
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/backend/faqs/index.blade.php
@extends('backend.layouts.app')

@section('title', trans('admin.faq'))

@section('content')
    <div class="mt-3">
        {!!
            grid([
                'dataProvider' => $dataProvider,
                'columnFields' => [
                [
                    'label' => trans('admin.question'),
                    'attribute' => 'question'
                ],
                [
                    'label' => trans('admin.language'),
                    'attribute' => 'language'
                ],
                [
                    'label' => trans('admin.status.status'),
                    'attribute' => 'status',
                    'value' => function($data) {
                        return \App\Enum\Status::get($data->status);
                    },
                    'filter' => [
                        'class' => Itstructure\GridView\Filters\DropdownFilter::class,
                        'data' => \App\Enum\Status::getList()
                    ]
                ],
                [
                    'label' => '',
                    'class' => Itstructure\GridView\Columns\ActionColumn::class,
                    'actionTypes' => [
                        'edit',
                        'delete' => function ($data) {
                            return route('admin.config.destroy', $data->id);
                        }
                    ]
                ]
            ]
            ])
        !!}
    </div>
@endsection

resources/views/backend/faqs/update.blade.php
@extends('backend.layouts.app')

@section('title', $faq->question)

@section('content')

    <div class="mt-3">
        <div>
            <form action="{{ route('admin.faq.update', $faq->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-primary">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="language">@lang('admin.language')</label>
                                    <select id="language" class="form-control @error('language') is-invalid @enderror" name="language">
                                        @foreach(LaravelLocalization::getSupportedLanguagesKeys() as $locale)
                                            <option value="{{$locale}}" @if($locale == old('language', $faq->language)) selected @endif>{{ $locale }}</option>
                                        @endforeach
                                    </select>
                                    @error('language')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="question">@lang('admin.question')</label>
                                    <input type="text" id="question" class="form-control @error('question') is-invalid @enderror" name="question" value="{{ old('question', $faq->question) }}">
                                    @error('question')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="answer">@lang('admin.answer')</label>
                                    <textarea id="answer" class="form-control @error('answer') is-invalid @enderror" name="answer" cols="30" rows="10">{{ old('answer', $faq->answer) }}</textarea>
                                    @error('answer')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>


                                <div class="form-group">
                                    <div class="float-right">
                                        <label for="status">@lang('admin.status.status')</label>
                                        <label class="switch switch-success">
                                            <input type="checkbox" name="status" id="status" @if($faq->status==1) checked @endif>
                                            <span class="slider round"></span>
                                        </label>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <input type="submit" value="@lang('admin.save')" class="btn btn-success float-right">
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection