routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\PostController;
use App\Http\Controllers\Backend\SiteController;
use App\Http\Controllers\Backend\BrandController;
use App\Http\Controllers\Backend\OrderController;
use App\Http\Controllers\Backend\SlideController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\CustomerController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\Auth\LoginController;
use App\Http\Controllers\Backend\PostCategoryController;

Route::middleware(['auth', 'preventBackHistory', 'role:admin'])->group(function () {
    Route::get('/', [SiteController::class, 'index'])->name('home');

    Route::get('property/get-list', [\App\Http\Controllers\Backend\PropertyController::class, 'getList'])->name('property.get-list');
    Route::resource('property', \App\Http\Controllers\Backend\PropertyController::class)->except(['show']);

    Route::resource('categories', CategoryController::class)->except(['show']);
    Route::get('categories/move/{id}/{type}', [CategoryController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('categories.move');


    Route::resource('brands', BrandController::class)->except(['show']);
    Route::get('brands/move/{id}/{type}', [BrandController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('brands.move');


    Route::resource('products', ProductController::class);
    Route::get('products-import', [ProductController::class, 'import'])->name('products.import');
    Route::post('products-importing', [ProductController::class, 'importProducts'])->name('products.import-products');

    Route::resource('slides', SlideController::class)->except('show');
    Route::get('slides/move/{id}/{type}', [SlideController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('slides.move');

    /* Page routes */
    Route::resource('pages', \App\Http\Controllers\Backend\PageController::class)->except(['show']);
    Route::post('pages/delete-image/{id}', [\App\Http\Controllers\Backend\PageController::class, 'deleteImage'])
        ->name('pages.delete-image');
    Route::get('pages/move/{id}/{type}', [\App\Http\Controllers\Backend\PageController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('pages.move');

    /* User routes */
    Route::post('users/delete-thumb/{id}', [\App\Http\Controllers\Backend\UserController::class, 'deleteThumb'])
        ->name('users.delete-image');
    Route::resource('users', \App\Http\Controllers\Backend\UserController::class);

    Route::resource('faq', \App\Http\Controllers\Backend\FaqController::class)->except(['show']);
    Route::resource('config', \App\Http\Controllers\Backend\ConfigController::class)->except(['show']);
    Route::resource('translates', \App\Http\Controllers\Backend\TranslateController::class)->except(['show']);

    /* Main Info routes */
    Route::post('main-info/delete-logo/{id}', [\App\Http\Controllers\Backend\MainInfoController::class, 'deleteLogo'])
        ->name('main-info.delete-logo');
    Route::post('main-info/delete-favicon/{id}', [\App\Http\Controllers\Backend\MainInfoController::class, 'deleteFavicon'])
        ->name('main-info.delete-favicon');
    Route::get('main-info', [\App\Http\Controllers\Backend\MainInfoController::class, 'index'])->name('main-info');
    Route::put('main-info', [\App\Http\Controllers\Backend\MainInfoController::class, 'update'])->name('main-info.update');

    /* Image Upload route */
    Route::post('ckeditor/image_upload', [\App\Http\Controllers\CkeditorController::class, 'upload'])->name('ckeupload');

    Route::resource('tags', \App\Http\Controllers\Backend\TagController::class);
    Route::prefix('blog')->name('blog.')->group(function () {
        Route::resource('categories', PostCategoryController::class);
        Route::get('categories/move/{id}/{type}', [PostCategoryController::class, 'move'])
            ->where('type', 'up|down')
            ->where('id', '[0-9]+')
            ->name('categories.move');
        Route::resource('posts', \App\Http\Controllers\Backend\PostController::class);
    });
    Route::get('posts/tag-list', [PostController::class, 'tagList'])->name('posts.tag-list');


    Route::resource('orders', \App\Http\Controllers\Backend\OrderController::class);
    Route::get('orders/reversal/{transaction_id}', [OrderController::class, 'reversal'])->name('orders.reversal');

    Route::resource('customers', CustomerController::class)->except(['show']);

    Route::prefix('photos')->name('photos.')->group(function () {
        Route::get('index', [\App\Http\Controllers\Backend\PhotoController::class, 'index'])->name('index');
        Route::get('folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderIndex'])->name('folder');
        Route::get('trash', [\App\Http\Controllers\Backend\PhotoController::class, 'trashIndex'])->name('trash');
        Route::get('restore', [\App\Http\Controllers\Backend\PhotoController::class, 'restore'])->name('restore');
        Route::post('create', [\App\Http\Controllers\Backend\PhotoController::class, 'create'])->name('create');
        Route::get('update', [\App\Http\Controllers\Backend\PhotoController::class, 'update'])->name('update');
        Route::post('update', [\App\Http\Controllers\Backend\PhotoController::class, 'update'])->name('update.submit');
        Route::post('size', [\App\Http\Controllers\Backend\PhotoController::class, 'size'])->name('size.submit');
        Route::get('create-folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderCreate'])->name('create-folder');
        Route::get('delete-folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderDelete'])->name('delete-folder');
        Route::get('update-folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderUpdate'])->name('update-folder');
        Route::post('update-folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderUpdate'])->name('update-folder.submit');
        Route::post('create-folder', [\App\Http\Controllers\Backend\PhotoController::class, 'folderCreate'])->name('create-folder.submit');
        Route::post('delete', [\App\Http\Controllers\Backend\PhotoController::class, 'delete'])->name('delete');
        Route::post('soft-delete', [\App\Http\Controllers\Backend\PhotoController::class, 'softDelete'])->name('softDelete');
        Route::post('crop', [\App\Http\Controllers\Backend\PhotoController::class, 'crop'])->name('crop');
        Route::get('sort', [\App\Http\Controllers\Backend\PhotoController::class, 'sort'])->name('sort');
        Route::post('render-gallery', [\App\Http\Controllers\Backend\PhotoController::class, 'renderGallery'])->name('render-gallery');
        Route::post('get-size', [\App\Http\Controllers\Backend\PhotoController::class, 'getSize'])->name('get-size');
    });

});

Route::middleware(['preventBackHistory'])->group(function () {
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->name('login.login');
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Frontend\SiteController;
use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\OrderController;
use App\Http\Controllers\Frontend\StaticController;
use App\Http\Controllers\Frontend\ContactController;
use App\Http\Controllers\Frontend\ProfileController;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;


Route::prefix(LaravelLocalization::setLocale())->middleware(['localize'])->group(function () {
    Route::get('/', [SiteController::class, 'index'])->name('home');

    Route::post('/product/fast-buy/{id}', [\App\Http\Controllers\Frontend\ProductController::class, 'fastBuy'])->name('fast-buy');

    Route::get('/products/filter', [\App\Http\Controllers\Frontend\ProductController::class, 'filter'])
        ->name('products.filter');
    Route::get('/products/{slug}', [\App\Http\Controllers\Frontend\ProductController::class, 'index'])
        ->where('slug', '[\w\-]+')
        ->name('products');

    Route::get('/search', [\App\Http\Controllers\Frontend\SearchController::class, 'index'])
        ->middleware(\App\Http\Middleware\SearchQuery::class)->name('search');
    Route::get('/search/filter', [\App\Http\Controllers\Frontend\SearchController::class, 'filter'])->name('search.filter');
    Route::get('/product/{slug}', [\App\Http\Controllers\Frontend\ProductController::class, 'index'])->name('products.category')
        ->where('slug', '[\w\-]+');
    Route::get('/product/{slug}', [\App\Http\Controllers\Frontend\ProductController::class, 'view'])->name('product')
        ->where('slug', '[\w\-]+');


    Route::get('/blog', [\App\Http\Controllers\Frontend\BlogController::class, 'index'])->name('blog.index');
    Route::name('blog.')->prefix('blog')->group(function () {
        Route::get('/{slug}', [\App\Http\Controllers\Frontend\BlogController::class, 'index'])->name('category')
            ->where('slug', '[\w\-]+');
        Route::get('/post/{slug}', [\App\Http\Controllers\Frontend\BlogController::class, 'view'])->name('post')
            ->where('slug', '[\w\-]+');
        Route::get('/tag/{slug}', [\App\Http\Controllers\Frontend\BlogController::class, 'tag'])->name('tag')
            ->where('slug', '[\w\-]+');
        Route::get('/search', [\App\Http\Controllers\Frontend\BlogController::class, 'search'])->name('search');
    });


    Route::get('/page/{slug}', [StaticController::class, 'view'])
        ->name('page')
        ->where('slug', '[\w\-]+');
    Route::get('/contact', [ContactController::class, 'index'])->name('contact');
    Route::get('/faq', [StaticController::class, 'faq'])->name('faq');
    Route::post('/contact/send', [ContactController::class, 'send'])->name('contact.send_message');

    Route::get('/favorites', [\App\Http\Controllers\Frontend\FavoriteController::class, 'index'])->name('favorites');
    Route::get('/favorite/add', [\App\Http\Controllers\Frontend\FavoriteController::class, 'add'])->name('favorite.add');
    Route::get('/favorite/remove', [\App\Http\Controllers\Frontend\FavoriteController::class, 'remove'])->name('favorite.remove');
    Route::get('/favorite/filter', [\App\Http\Controllers\Frontend\FavoriteController::class, 'filter'])->name('favorite.filter');



    Route::get('/cart', [CartController::class, 'index'])->name('cart');
    Route::get('/cart/add', [\App\Http\Controllers\Frontend\CartController::class, 'add'])->name('cart.add');
    Route::get('/cart/update', [\App\Http\Controllers\Frontend\CartController::class, 'update'])->name('cart.update');
    Route::get('/cart/remove', [\App\Http\Controllers\Frontend\CartController::class, 'remove'])->name('cart.remove');

    Route::get('/checkout', [\App\Http\Controllers\Frontend\CheckoutController::class, 'index'])->name('checkout');

    Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
        Route::post('/send', [OrderController::class, 'send'])->name('send');
        Route::get('/thank-you', [OrderController::class, 'thankYou'])->name('thankYou');
        Route::get('/payment-result', [OrderController::class, 'paymentResult'])->name('payment.result');
        Route::get('/fail', [OrderController::class, 'fail'])->name('fail');
    });

    Route::group(['middleware' => ['auth:siteCustomer']], function () {
        Route::get('/history', [ProfileController::class, 'history'])->name('history');
        Route::get('/history/{id}', [ProfileController::class, 'historyView'])->name('history.view');
        Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
        Route::get('/profile/change-password', [ProfileController::class, 'changePasswordForm'])->name('profile.change-password');
        Route::put('/profile/change-password', [ProfileController::class, 'changePassword'])->name('profile.change-password.submit');
        Route::put('/profile/update', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::get('/profile/delete', [ProfileController::class, 'delete'])->name('profile.delete');
    });

    Route::middleware(['preventBackHistory'])->group(function () {
        Route::get('login', [\App\Http\Controllers\Frontend\Auth\LoginController::class, 'showLoginForm'])->name('login');
        Route::post('login', [\App\Http\Controllers\Frontend\Auth\LoginController::class, 'login'])->name('login.submit');
        Route::get('register', [\App\Http\Controllers\Frontend\Auth\RegisterController::class, 'showRegistrationForm'])->name('register');
        Route::post('register', [\App\Http\Controllers\Frontend\Auth\RegisterController::class, 'register'])->name('register.submit');
        Route::get('logout', [\App\Http\Controllers\Frontend\Auth\LoginController::class, 'logout'])->name('logout');

        Route::get('reset-password', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'showResetPasswordForm'])->name('reset-password');
        Route::post('reset-password', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'showResetPasswordForm'])->name('reset-password.submit');
        Route::get('send-reset-code', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'showCodeInputForm'])->name('show-code-form');
        Route::post('send-reset-code', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'showCodeInputForm'])->name('show-code-form.submit');
        Route::get('change-password', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'changePassword'])->name('change-password');
        Route::post('change-password', [\App\Http\Controllers\Frontend\Auth\ResetPasswordController::class, 'changePassword'])->name('change-password.submit');
    });
});

resources/views/widgets/blog_sidebar.blade.php
<div class="blog_sidebar_widget">

{{--    <div class="widget_list widget_search">--}}
{{--        <div class="widget_title">--}}
{{--            <h3>@lang('site.blog.search_title')</h3>--}}
{{--        </div>--}}
{{--        <form action="{{ route('blog.search') }}">--}}
{{--            <input name="query" placeholder="@lang('site.blog.write_search')" type="text">--}}
{{--            <button type="submit">@lang('site.blog.search')</button>--}}
{{--        </form>--}}
{{--    </div>--}}

    @if(!$topPosts->isEmpty())
        <div class="widget_list widget_post">
            <div class="widget_title">
                <h3>@lang('site.blog.popular_posts')</h3>
            </div>
            @foreach($topPosts as $topPost)
                <div class="post_wrapper">
                    <div class="post_thumb">
                        <a href="{{ route('blog.post', $topPost->slug) }}"><img src="{{ post_image($topPost->image) }}" alt="{{ $topPost->title }}"></a>
                    </div>
                    <div class="post_info">
                        <h4><a href="{{ route('blog.post', $topPost->slug) }}">{{ $topPost->title }}</a></h4>
                        <span>{{ $topPost->published_at }}</span>
                    </div>
                </div>
            @endforeach
        </div>
    @endif

    @if(!$categories->isEmpty())
        <div class="widget_list widget_categories">
            <div class="widget_title">
                <h3>@lang('site.blog.categories')</h3>
            </div>
            <ul>
                @foreach($categories as $category)
                    <li><a href="{{ route('blog.category', $category->slug) }}">{{ $category->title }}</a></li>
                @endforeach
            </ul>
        </div>
    @endif

    @if(!$tags->isEmpty())
        <div class="widget_list widget_tag">
            <div class="widget_title">
                <h3>@lang('site.blog.tags')</h3>
            </div>
            <div class="tag_widget">
                <ul>
                    @foreach($tags as $tag)
                        <li><a href="{{ route('blog.tag', $tag->slug) }}">{{ $tag->name }}</a></li>
                    @endforeach
                </ul>
            </div>
        </div>
    @endif
</div>

resources/views/widgets/blog_widget.blade.php
@if($posts->count())
    <!-- Blog -->
    <section class="blog m-top">
        <div class="container-fluid">
            <h2 class="section-title">@lang('site.layout.blog')</h2>
            <div class="row">
                @foreach($posts as $post)
                    <div class="col-md-4">
                        <a href="{{ route('blog.post', $post->slug) }}" class="blog__item">
                            <div class="blog__image"><img src="{{ asset('storage/posts/' . $post->image) }}" alt="{{ $post->title }}"></div>
                            <div class="blog__text">
                                <h2>{{ $post->title }}</h2>
                                <p>{{ \App\Helpers\StringHelper::clearContent($post->description) }}</p>
                                <span>
                                    @lang('site.blog.read_more')
                                    <svg xmlns="http://www.w3.org/2000/svg" width="1.4rem" height="1.4rem">
                                        <use xlink:href="#svg-arrow-right"></use>
                                    </svg>
                                </span>
                            </div>
                        </a>
                    </div>
                @endforeach
            </div>
        </div>
    </section>
    <!-- End Blog -->
@endif

resources/views/widgets/brand_slider.blade.php
@if(!$brands->isEmpty())
    <!-- Partners -->
    <section class="partners m-top">
        <div class="container-fluid">
            <h2 class="section-title">@lang('site.layout.brands')</h2>
            <div class="row partners__slider m-0">
                @foreach($brands as $brand)
                    <div class="col-md-2">
                        <a href="{{ $brand->link }}"><img src="{{ asset('storage/brands/' . $brand->image) }}" alt="{{ $brand->title }}"></a>
                    </div>
                @endforeach
            </div>
        </div>
    </section>
    <!-- End Partners -->
@endif

resources/views/widgets/cart_widget.blade.php
{{--<div class="header__basket">--}}
{{--    <div class="basket__item">--}}
{{--        <a href="#" class="basket__image"><img src="/assets/front/images/prod3.jpg" alt=""></a>--}}
{{--        <div class="basket__info">--}}
{{--            <a href="#" class="products__title">Shell Helix Ultra 5W-40 5lt</a>--}}
{{--            <span class="products__price__new">86.00 AZN</span>--}}
{{--            <div class="basket__count">--}}
{{--                <button class="basket__count__btn basket__count__btn--minus" disabled>--}}
{{--                    <svg xmlns="http://www.w3.org/2000/svg" width="2.0rem" height="2.2rem">--}}
{{--                        <use xlink:href="#svg-minus"></use>--}}
{{--                    </svg>--}}
{{--                </button>--}}
{{--                <input type="number" class="basket__count__input" value="1" max="10">--}}
{{--                <button class="basket__count__btn basket__count__btn--plus">--}}
{{--                    <svg xmlns="http://www.w3.org/2000/svg" width="2.0rem" height="2.2rem">--}}
{{--                        <use xlink:href="#svg-plus"></use>--}}
{{--                    </svg>--}}
{{--                </button>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}
{{--    <div class="basket__item">--}}
{{--        <a href="#" class="basket__image"><img src="/assets/front/images/prod3.jpg" alt=""></a>--}}
{{--        <div class="basket__info">--}}
{{--            <a href="#" class="products__title">Shell Helix Ultra 5W-40 5lt</a>--}}
{{--            <span class="products__price__new">86.00 AZN</span>--}}
{{--            <div class="basket__count">--}}
{{--                <button class="basket__count__btn basket__count__btn--minus" disabled>--}}
{{--                    <svg xmlns="http://www.w3.org/2000/svg" width="2.0rem" height="2.2rem">--}}
{{--                        <use xlink:href="#svg-minus"></use>--}}
{{--                    </svg>--}}
{{--                </button>--}}
{{--                <input type="number" class="basket__count__input" value="1" max="10">--}}
{{--                <button class="basket__count__btn basket__count__btn--plus">--}}
{{--                    <svg xmlns="http://www.w3.org/2000/svg" width="2.0rem" height="2.2rem">--}}
{{--                        <use xlink:href="#svg-plus"></use>--}}
{{--                    </svg>--}}
{{--                </button>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}
{{--    <a href="#" class="btn btn-orange-transparent btn--sm w-100 fw-400 mt-4">Səbətə bax</a>--}}
{{--    <a href="#" class="btn btn-orange btn--sm w-100 fw-400 mt-4">Sifarişi tamamla</a>--}}
{{--</div>--}}

resources/views/widgets/currency.blade.php
@if(!empty($currencies))
    <div class="currency-block">
        <div class="container">
            <div class="owl-carousel owl-theme currency-slider">
                @foreach($currencies as $code => $currency)
                    @if(isset($currency[1]) && $currency[0] < $currency[1])
                        @php
                            /**@var $currency **/
                                $decrement=round(($currency[1]-$currency[0])/$currency[1]*100,2)
                        @endphp
                        <div class="cur-box down d-flex item">
                            <i class="arrow"></i>
                            <p>{{$code}} <span>{{$currency[0]}}</span></p>
                        </div>
                    @else
                        <div class="cur-box up d-flex item">
                            <i class="arrow"></i>
                            <p>{{$code}} <span>{{$currency[0]}}</span></p>
                        </div>
                    @endif
                @endforeach

            </div>
        </div>
    </div>
@endif

resources/views/widgets/lang_switcher.blade.php
@php
    $lang = app()->getLocale();
@endphp
<div class="header__lang no-icon">
    <div class="header__lang__selected">
        <span><img src="/assets/front/images/{{$lang}}.svg" alt=""></span>
        @lang('site.lang.' . $lang)
    </div>
    @if(count($langs = LaravelLocalization::getSupportedLanguagesKeys()) > 1)
        <ul class="header__lang__list">
            @foreach($langs as $locale)
                @if($locale != $lang)
                    <li>
                        <a href="{{ LaravelLocalization::localizeURL(url()->current(), $locale) }}">
                            <span><img src="/assets/front/images/{{$locale}}.svg" alt="@lang('site.lang.' . $locale)"></span> @lang('site.lang.' . $locale)
                        </a>
                    </li>
                @endif
            @endforeach
        </ul>
    @endif
</div>

resources/views/widgets/main_filter.blade.php
<div class="main__filter">
    @if($categories->isNotEmpty())
        <div class="main__filter__tab">
            @foreach($categories as $key => $category)
                <a href="javascript:void(0);" class="@if($key == 0) active @endif btn btn-gray btn--sm tab__item" data-tab="tab{{ $category->id}}">{{ $category->title}}</a>
            @endforeach
        </div>
        <div class="tab-content">
            @foreach($categories as $key => $category)
                <form class="tab-content__item @if($key == 0) active @endif" data-tab="tab{{ $category->id}}" method="GET" action="{{ route('products', $category->slug) }}">
                    <div class="form-group">
                        <label>@lang('site.filter.brand')</label>
                        <select class="form-control  custom-select" name="brand[]">
                            <option value>@lang('site.filter.choose')</option>
                            @foreach($category->brands as $brand)
                                <option value="{{ $brand->slug }}">{{ $brand->title }}</option>
                            @endforeach
                        </select>
                    </div>
                    @foreach($category->mainProperties as $property)
                        <div class="form-group">
                            <label>{{ $property->title }}</label>
                            <select class="form-control custom-select" name="filter[{{ $property->slug }}][]">
                                <option value>@lang('site.filter.choose')</option>
                                @foreach($property->relates as $relate)
                                    <option value="{{ $relate->value }}">{{ $relate->value }}</option>
                                @endforeach
                            </select>
                        </div>
                    @endforeach
                    <div class="main__filter__btns">
                        <button type="submit" class="btn btn--sm btn-orange">@lang('site.filter.search')</button>
                        <button type="reset" class="btn btn--sm btn-orange-transparent">@lang('site.filter.reset')</button>
                    </div>
                </form>
            @endforeach
        </div>
    @endif
</div>

resources/views/widgets/menu-footer.blade.php
<div class="col d-md-flex">
    @if($servicePages->isNotEmpty())
        <div class="footer__item">
            <h3 class="footer__title">@lang('site.layout.services')</h3>
            <ul class="footer__menu">
                @foreach($servicePages as $servicePage)
                    <li><a href="{{ route('page', $servicePage->slug) }}">{{ $servicePage->title }}</a></li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="footer__item">
        <h3 class="footer__title">@lang('site.layout.about_company')</h3>
        <ul class="footer__menu">
            @if($defaultPages->isNotEmpty())
                @foreach($defaultPages as $defaultPage)
                    <li><a href="{{ route('page', $defaultPage->slug) }}">{{ $defaultPage->title }}</a></li>
                @endforeach
            @endif
            <li><a href="{{ route('blog.index') }}">@lang('site.layout.blog')</a></li>
            <li><a href="{{ route('faq') }}">@lang('site.layout.faq')</a></li>
            <li><a href="{{ route('contact') }}">@lang('site.layout.contact')</a></li>
        </ul>
    </div>
    <div class="footer__item">
        <h3 class="footer__title">@lang('site.layout.contact_info')</h3>
        <ul class="footer__menu">
            @foreach(site_info('email') as $email)
                <li><a href="mailto:{{ $email }}">{{ $email }}</a></li>
            @endforeach
            @foreach(site_info('phone') as $phone)
                <li><a href="tel:{{ $phone }}">{{ $phone }}</a></li><br>
            @endforeach
            {{ site_info('address') }}
        </ul>
    </div>
</div>

resources/views/widgets/menu-header.blade.php
<li><a class="@if(Route::is('home') || Route::currentRouteName() == '') active @endif"  href="{{ route('home') }}">@lang('site.layout.home')</a></li>
@foreach($categories as $category)
    <li><a href="{{ route('products', $category->slug) }}" class="@if(request('slug') == $category->slug) active @endif">{{ $category->title }}</a></li>
@endforeach

resources/views/widgets/menu-mobile-header.blade.php
<ul class="offcanvas_main_menu">
    <li class="menu-item-has-children"><a class="active"  href="{{ route('home') }}">@lang('site.layout.home')</a></li>
    <li class="menu-item-has-children"><a href="{{ route('products') }}">@lang('site.layout.products')</a></li>
    <li class="menu-item-has-children"><a href="{{ route('blog.index') }}">@lang('site.layout.blog')</a></li>

    @if(!$pages->isEmpty())
        @foreach($pages as $page)
            <li class="menu-item-has-children"><a href="{{ route('page', $page->slug) }}">{{ $page->title }}</a></li>
        @endforeach
    @endif

    <li class="menu-item-has-children"><a href="{{ route('contact') }}">@lang('site.layout.contact-us')</a></li>
</ul>

resources/views/widgets/product_sidebar.blade.php
<!--sidebar widget start-->
<aside class="sidebar_widget filters" data-url="{{ route('products', ['search' => request()->get('search')]) }}">

    <div class="widget_list widget_filter">
        <h3>@lang('site.product.filter_price')</h3>
        <form action="#">
            <div id="slider-range"></div>
            <input type="text" name="price" id="amount"  data-max="{{ get_price($maxPrice) }}"
                   data-start-value="{{ request()->input('filters.startPrice') }}"
                   data-end-value="{{ request()->input('filters.endPrice') }}"
            />
        </form>
    </div>
    @if(!$brands->isEmpty())
        <div class="widget_list widget_categories">
            <h3>@lang('site.product.filter_manufacturers')</h3>
            <ul>
                @foreach($brands as $brand)
                    <li>
                        <input id="{{ $brand->slug }}" value="{{ $brand->slug }}" @if(in_array($brand->slug, request()->input('filters.brand') ?? [])) checked @endif type="checkbox" name="brand[{{ $brand->id }}]" class="filter-brand">
                        <label for="{{ $brand->slug }}">{{ $brand->title }}</label>
                        <span class="checkmark"></span>
                    </li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="widget_list widget_filter">
        <button type="button" class="submitFilter">@lang('site.product.filter')</button>
    </div>

</aside>
<!--sidebar widget end-->